### ISSUE TITLE
Bug Report: <BUG>

### ISSUE THREAD

**Issue by anttirautanen** [CircleCI-Public/cimg-mariadb#55]
**Describe the bug**

The MariaDB version that is started is not the same version as in the image's tag. It seems that the started version is `10.11.7`, even though I used the tag `10.11.6`.

I have a job configuration like this:

```yml
  phpunit:
    docker:
      - image: cimg/php:8.3.4
      - image: cimg/mariadb:10.11.6
        environment:
          MARIADB_ROOT_PASSWORD: <password>
          MARIADB_DATABASE: <dbname>
          MARIADB_USER: <username>
          MARIADB_PASSWORD: <password>
```

Note the image and tag `cimg/mariadb:10.11.6`.

The CircleCI output for that job has a step called `Container cimg/mariadb:10.11.6`. The actual output of the step has following lines:

```
2024-06-15 08:33:11+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 10.11.7 started.
```

```
2024-06-15  8:33:12 0 [Note] Starting MariaDB 10.11.7-MariaDB-1:10.11.7+maria~ubu2204 source revision 87e13722a95af5d9378d990caf48cb6874439347 as process 169
```

**To Reproduce**

Start a job with image `cimg/mariadb:10.11.6` and check the output of step `Container cimg/mariadb:10.11.6`.

```yml
version: 2.1
jobs:
  dummyjob:
    docker:
      - image: cimg/mariadb:10.11.6
        environment:
          MARIADB_ROOT_PASSWORD: rootpassword
          MARIADB_DATABASE: testdb
          MARIADB_USER: testuser
          MARIADB_PASSWORD: testpassword
    steps:
      - checkout
      - run:
          name: Dummy step
          command: echo "Hello, World!"

workflows:
  version: 2
  dummyworkflow:
    jobs:
      - dummyjob
```

**Expected behavior**

I expect to get MariaDB `10.11.6` with the image `cimg/mariadb:10.11.6`

**Screenshots and Build Links**

![Screenshot 2024-06-15 at 11 48 37](https://github.com/CircleCI-Public/cimg-mariadb/assets/572227/c88866b3-4c5c-45c4-bfc0-835fe8a640fb)
